[31기 노영완]ADD: footer구현
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend pull request #10
Opened 2022-04-04 03:35 UTC by nohnohnohnoh

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 각각 페이지에 해당 적용되는 footer 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 큰 부모 태그로 묶은 후 Ul 태그와 li 태그로 footer box 구현 줄 띄우는 p태그 사용해 직관적으로 보이기에 편하게 구현 css에 line-height를 사용해 줄띄움을 더욱 직관적으로 보이게에 편하게 구현 inline-block속성을 줌으로써 flex를 사용하지 않고 원하는 구현목표로 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
html의 부모태그를 묶는 부분에 있어서 많이 부족하다고 생각했는데 html의 구조를 파악하는데 도움이 많이 되었다. 박스태그를 움직이는데 있어서 flex를 쓰는게 아닌 inline-block을 주어서 구현할 수 있는데에도 도움이 되었다. 가장 큰 공부는 html의 구조를 다시 한번 파악하는데 도움이 정말 많이 되었다

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-04 06:42 UTC, younuk23 commented
리뷰 요청 라벨 부착해주세요~!

2022-04-04 08:10 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!!

그리고 라벨 꼼꼼히 확인해주세요! 지금은 수정요청이랑 리뷰요청라벨을 같이 붙이셨네요
PR 제목, 본문, 라벨은 소통의 기본입니다 꼼꼼히 확인해주세요!

2022-04-04 08:10 UTC, yeonuk-hwang commented on src/components/Footer/Footer.scss
> +}
- nesting 적용해주세요!!

- 일관적으로 다른 셀렉터들끼리는 공백 부여해주세요, 지금은 공백이 처리 된 것도 있고, 안된것도 있어서 가독성이 좋지 않네요,

- CSS 속성은 레이아웃에 영향을 많이 주는 순서대로, 인접 속성끼리 묶어서 
작성해주는게 좋습니다. 2주차에 안내해드린 리팩토링 체크리스트 참고해서 속성순서 맞춰주세요!

2022-04-04 08:10 UTC, yeonuk-hwang commented on src/components/Footer/Footer.js
> +            <div className="lb-wrap">
camelCase or snake_case 하나로 통일해주세요!(팀 내에서 하나로 통일되어야 합니다)

2022-04-04 09:01 UTC, nohnohnohnoh commented on src/components/Footer/Footer.js
> +            <div className="lb-wrap">
감사합니다 연욱님 footer branch 수정 완료하였습니다!!

2022-04-05 01:50 UTC, younuk23 requested changes
간단한 수정사항 있습니다! 수정해주세요!

2022-04-05 01:50 UTC, younuk23 commented on src/components/Footer/Footer.js
> +    <div className="widthFooter">
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetial">
			~~~~
		</section>
	)
}
``` 

className 코멘트 참고하셔서 수정해주세요!

2022-04-05 01:50 UTC, younuk23 commented on src/components/Footer/Footer.scss
> +}
- 아직 네스팅이 안되었네요 이부분은 수정해주세요! 
- css 셀렉터 사이에 공백 한줄씩 부여해주세요!

2022-04-06 01:59 UTC, younuk23 commented
컨플릭 해결해주세요!

2022-04-06 05:26 UTC, younuk23 approved these changes
LGTM 👍

2022-04-06 05:26 UTC, merged