[31기 남용현] ADD: 장바구니 페이지 구현
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend pull request #11
Opened 2022-04-04 04:24 UTC by sunnyfterrain

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 장바구니 페이지 UI 구현
- mock 데이터를 이용 장바구니 페이지 테스트구현
- 상세페이지와 장바구니 페이지 연동

<br />

## :: 구현 사항 설명 
1. 장바구니 페이지 UI 구현
- mock 데이터를 이용 장바구니 페이지 구현
- 전체 삭제 구현 (개별 삭제 구현중)

2. 상품 상세페이지에서 장바구니로 이동시 장바구니 이동 모달창 연동

<br />

## :: 성장 포인트
- 프론트 단에서 상품별 장바구니 이동 구현은 해보았지만 백엔드와 연동은 처음이었습니다.
- 백엔드로 상품을 보내고 다시 백엔드 장바구니 DB에서 자료를 받아오는걸 직접해보니 새로웠습니다.
<br />

## :: 기타 질문 및 특이 사항

2022-04-04 07:52 UTC, younuk23 requested changes
고생하셨습니다 용현님! 리뷰 요청 전 사이더 코멘트는 다 해결해주세요!!
리뷰 확인 및 반영해주세요!

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +  }, []);
useEffect의 callback으로 async function을 넣는것은 좋지 않습니다.

effect안에서 async처리를 하는 방법에 대해서는 검색해보시면 즉시실행함수, inner function 활용 등 여러방법이 있으니 찾아보시고 선택하셔서 적용해주세요!

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +      'http://localhost:3000/data/cartData.json'
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    getCartData.cart_list.length ? setIsCartValid(true) : setIsCartValid(false);
cartIsValid라는 값이 cartItem의 length에 의해서 결정되는 값이라면 굳이 또 하나의 state로 만들 필요가 없어보이네요!

아래 내용 읽어보시고 왜 필요 없는지 한번 생각해보세요!

[공식문서 React로 사고하기](https://ko.reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state) 를 보시면 어떤 값들이 state가 되어야하는지에 대해 적혀있습니다.

> 각각 살펴보고 어떤 게 state가 되어야 하는 지 살펴봅시다. 이는 각 데이터에 대해 아래의 세 가지 질문을 통해 결정할 수 있습니다
> 

> 1. 부모로부터 props를 통해 전달됩니까? 그러면 확실히 state가 아닙니다.
> 

> 2. 시간이 지나도 변하지 않나요? 그러면 확실히 state가 아닙니다.
> 

> 3. 컴포넌트 안의 다른 state나 props를 가지고 계산 가능한가요? 그렇다면 state가 아닙니다.
>

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/CartItem.js
> +  const [count, setCount] = useState(quantity);
두개의 state가 모두 필요한 이유가 없어보입니다. 하나의 값을 표현하기위해서  두개의 state를 활용하는 느낌이네요

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/ValidCart.js
> +  const TITLE_LIST = ['ITEM', 'NAME', 'PRICE', 'QUANTITY', 'REMOVE'];
- 이 값 같은 경우에는 매 rendering 마다 새롭게 선언되고 할당될 필요는 없어보입니다.
- 이런 상수데이터를  함수형 컴포넌트 본문 안에서 선언하게 되면 rendering이 일어날때 마다 매번 데이터를 만들고 변수에 값을 할당하는 연산이 일어나게 됩니다.
- 따라서 성능에 악영향을 미칠 수 있습니다.
- 컴포넌트가 사용하는 데이터라고 컴포넌트 안에만 위치할 필요는 없습니다
- 통상 이런 상수데이터같은 경우에는 여러 컴포넌트에서 동시에 사용하는 데이터라면 별도 파일로 분리하거나,이 컴포넌트 안에서만 사용하는 데이터라면 컴포넌트 하단에 작성해줍니다
- 상수데이터의 네이밍은 상수데이터임을 표시하기 위해서 UPPERCASER + snake_case 로 작성해주는게 컨벤션입니다

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/ValidCart.js
> +  const [checkedList, setCheckedList] = useState(cartItem);
이 state는 사용되는 부분이 없어보이네요

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/ValidCart.js
> +          {cartItem?.map((cartData, idx) => {
Data등의 이름은 굳이 변수명이 넣을 필요가 없습니다. 오히려 혼란을 가중시키는 역할을 합니다.

```suggestion
          {carts?.map((cart, idx) => {
```

이런식으로 처리되는게 좋겠네요!

2022-04-04 07:52 UTC, younuk23 commented on src/pages/Cart/ValidCart.js
> +                key={id}
여기서의 id는 useParams hook에서 꺼내온 id가 들어가네요, 그러면 모든 아이템이 다 같은 key값을 부여받게되서 key가 제대로 동작하지 않을 것 같네요

이렇게되면 console창에서 해당부분 경고하는 워닝이 출력됩니다!

PR등록하기전 console에서 드는 warning도 잘 확인하고 왜 뜨는지, 어떻게 없앨 수 있는지 고민해보시면 좋습니다!

2022-04-04 09:14 UTC, sunnyfterrain commented on src/pages/Cart/ValidCart.js
> +                key={id}
기존 객체 안에 들어있는 id로 변경 완료하였습니다.!

2022-04-04 09:14 UTC, sunnyfterrain commented on src/pages/Cart/ValidCart.js
> +          {cartItem?.map((cartData, idx) => {
수정하였습니다.

2022-04-04 09:15 UTC, sunnyfterrain commented on src/pages/Cart/ValidCart.js
> +  const TITLE_LIST = ['ITEM', 'NAME', 'PRICE', 'QUANTITY', 'REMOVE'];
상수데이터 위치 변경하였습니다

2022-04-04 09:17 UTC, sunnyfterrain commented on src/pages/Cart/CartItem.js
> +  const [count, setCount] = useState(quantity);
quanInput은 카운트 스테이트를 인풋 value에 고정값으로 넣고 직접 입력하여 수정할수있게 하나는 인풋으로 준것인데 다른 방법을 연구해보겠습니다 ㅠㅠ지금 고치기가 너무 어려워요

2022-04-04 09:18 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +    getCartData.cart_list.length ? setIsCartValid(true) : setIsCartValid(false);
삼항연산자 없이 바로 스테이트에 블린을 적용하게 수정하였습니다.

2022-04-04 09:18 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +      'http://localhost:3000/data/cartData.json'
생략 하였습니다!

2022-04-04 09:18 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +  }, []);
네! 활용방법 검색하여 다시 적용하였습니다.

2022-04-05 02:26 UTC, younuk23 requested changes
코멘트 남겼습니다 확인하고 수정해주세요!

2022-04-05 02:26 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    // console.log(getCartData.cart_list);
불필요한 주석은 삭제해주세요!

코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.

그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 

따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-04-05 02:26 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    getCartData.cart_list.length ? setIsCartValid(true) : setIsCartValid(false);
여전히 불필요한 isCartValid라는 state가 들어있습니다.
carts에 값이 있는지 없는지 확인하기 위한 값이라면, carts라는 state를 통해서 바로 변수로 선언해서 활용할 수 있지 않을까요?

2022-04-05 02:26 UTC, younuk23 commented on src/pages/Cart/CartItem.js
> +  console.log('cart 카운트:', count);
sider 코멘트 반드시 다 해결해주세요,

2022-04-05 02:26 UTC, younuk23 commented on src/pages/Cart/CartItem.js
> +  const [count, setCount] = useState(quantity);
다른 기능들 이것저것 만드는 것 보다 이걸 고치는게 더 도움이 될 것 같네요

누누히 말하지만 많이 했다고, 겉보기에 화려하다고 프로젝트를 잘 한게 아닙니다.

그 안에서 내가 얼마나 고민하고 배웠는지, 그리고 팀원들과 어떻게 협력했는지가 우리가 남겨야할 결과물입니다.

이부분은 충분히 고민해보시고 수정해주세요!

2022-04-05 05:28 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +    // console.log(getCartData.cart_list);
추후 백엔드 연결시 사용될 코드로 TODO 주석을 달아놓았습니다.

2022-04-05 05:34 UTC, sunnyfterrain commented on src/pages/Cart/ValidCart.js
> +  const [checkedList, setCheckedList] = useState(cartItem);
삭제 하였습니다!

2022-04-05 05:42 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +    getCartData.cart_list.length ? setIsCartValid(true) : setIsCartValid(false);
스테이트를 없애고 변수 하나를 만들어 boolean 을 적용하였습니다.

2022-04-05 05:49 UTC, sunnyfterrain commented on src/pages/Cart/CartItem.js
> +  const [count, setCount] = useState(quantity);
하나로 합쳤습니다!! 생각을 잘못한거 같아요. 스테이트를 무조건적으로 만든 느낌이었습니다.

2022-04-05 07:28 UTC, younuk23 reviewed
리뷰 확인해주세요~!

2022-04-05 07:28 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    // console.log(getCartData.cart_list);
주석으로 남겨두는것 보다 지우고, 나중에 수정해주는게 좋겠네요

아래의 getCardData 코드와 동일한 항목으로 보여서 나중에 주소만 변경하는식으로 적용하는게 좋아보이네요

2022-04-05 07:28 UTC, younuk23 commented on src/pages/Cart/CartItem.js
> +    count: 1,
기존의 리뷰가 하나로 합치라고 해서 하나의 객체안에 property로 넣는것을 의미한것은 아닙니다.

input과 count 두개의 값이 모두 필요하지 않아보입니다 실제로 UI에서 count라는 값은 보여지는데에 사용되지 않고 있습니다.

2022-04-05 07:28 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +/* eslint-disable */
다른 PR에서 남긴 코멘트와 동일한 부분이네요
급하게 막 하기보다는 항상 꼼꼼하게 확인하는 습관을 들여주세요!!

push하고 나서 꼭 file changed 탭 확인해서 본인의 작업물에 실수는없는지 확인해주세요

2022-04-05 07:28 UTC, younuk23 commented on src/pages/Cart/CartItem.js
> +    if (count < 2) {
start하면 에러발생할 것 같네요 확인해보셨나요??
자신의 코드와 결과물에 대해서 책임감을 가지고 꼭 꼼꼼히 확인해주세요!!
프로젝트가 막바지로간다고 급한마음에 빠르게만하면 안됩니다.

2022-04-05 07:33 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +    // console.log(getCartData.cart_list);
주석 삭제하였습니다. 나중에 api 사용시 해당 주소부분만 변경하도록 하겠습니다.

2022-04-05 07:44 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +/* eslint-disable */
너무 급했네요ㅠ 수정하였습니다.

2022-04-05 08:35 UTC, sunnyfterrain commented on src/pages/Cart/CartItem.js
> +    count: 1,
왜 혼자 할때는 그런것들을 생각 못하는지 모르겠습니다ㅠ 차근차근 다시 보고 수정하였습니다.

2022-04-05 08:36 UTC, sunnyfterrain commented on src/pages/Cart/CartItem.js
> +    if (count < 2) {
조건문으로 주어야할 사항 다시 확인하여 적용 하였습니다. 천천히 차근차근 다시 살펴보겠습니다

2022-04-06 02:05 UTC, younuk23 approved these changes
LGTM 👍
코멘트 하나 남긴건 다음 작업할 때 반영해주세요!

2022-04-06 02:05 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    const MOCK_CART = 'data/cartData.json';
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2022-04-06 02:05 UTC, merged

2022-04-06 02:36 UTC, sunnyfterrain commented on src/pages/Cart/Cart.js
> +    const MOCK_CART = 'data/cartData.json';
절대경로로 수정하였습니다!!