[31기 남용현] MODIFY: context 관련 수정
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend pull request #13
Opened 2022-04-04 15:50 UTC by sunnyfterrain

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
1. 컨텍스트 관련 코드 추가

<br />

## :: 구현 사항 설명 
1. 컨텍스트 관련 코드 추가
- 상품페이지 PR 에서 리뷰받은 로그인관련 컨텍스트 관리로 인해 관련 코드 추가
- 기존의 전달받던 props를 제거하고 컨텍스트로 받은 데이터 사용

<br />

## :: 성장 포인트 
야심차게 사용해본 컨텍스트 이지만 fetch 자료말고 스테이트도 따로 전달, 혹은
복수의 value값을 전달하는 방법을 잘 몰랐는데 이번 기회에 알게 되었고 사용해보게 되어서 좋았습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-04-05 02:29 UTC, younuk23 reviewed
이 작업은 기존 작업이 머지되어야지 돌아갈 수 있는 코드같네요
지금 머지된다면 바로 에러가 발생할 것 같습니다.

항상 master 기준으로 지금 돌아가는지를 잘 확인해주세요

기존 Context login 부분 머지되고 나서 다시 리뷰요청 해주세요!

2022-04-05 07:31 UTC, yeonuk-hwang requested changes
리뷰 확인 및 반영해주세요!

2022-04-05 07:31 UTC, younuk23 commented on src/components/Header/Header.js
> +  const NAV_LIST = [
NAV_LIST 사이의 빈문자열이 공백을 위한 것이라면 CSS로 처리하는게 좋겠네요!! 이 데이터는 Nav안에 나타날 아이템들을 표현하기 위함인데 스타일링만을 위한 요소들이 들어가는것은 좋지않습니다!

2022-04-05 09:15 UTC, sunnyfterrain commented on src/components/Header/Header.js
> +  const NAV_LIST = [
빈 공백을 지우고, css로 스타일을 주었습니다!

2022-04-06 02:06 UTC, younuk23 approved these changes
LGTM 👍

2022-04-06 02:06 UTC, merged