Feature/nav
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend pull request #2
Opened 2022-03-29 02:37 UTC by sunnyfterrain

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 공통 nav 제작

<br />

## :: 구현 사항 설명 (
1. navBar 메뉴 제작
- 기능구현 없이 단순 정적인 nav ui 구현

<br />

## :: 성장 포인트 

<br />

## :: 기타 질문 및 특이 사항

2022-03-29 05:59 UTC, younuk23 requested changes
고생하셨습니다 용현님!
- PR 제목 양식 맞춰주시고
- 라벨도 잘 붙여주세요 :)

2022-03-29 05:59 UTC, younuk23 commented on jsconfig.json
> -}
이부분은 왜 삭제하신건가요?

2022-03-29 05:59 UTC, younuk23 commented on src/components/Header/Header.js
> -  return <div>Header</div>;
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetial">
			~~~~
		</section>
	)
}
```

2022-03-29 05:59 UTC, younuk23 commented on src/components/Header/Header.scss
> +header {
위에 드린 코멘트와 연관되는 내용으로 이렇게 되면 프로젝트 내에 모든 header tag에 이 스타일이 적용되어 버리겠네요

2022-03-29 05:59 UTC, younuk23 commented on src/components/Header/Header.scss
> +    flex-direction: column;
필요한 속성인가요? 아래에 해당되는 태그들이 다 block 이라서 굳이 flex, column 안해도 세로 쌓임으로 동작할 것 같습니다!

2022-03-29 05:59 UTC, younuk23 commented on src/components/Header/Header.scss
> +    h3 {
- div 태그 처럼 빈번히 사용되는 태그로 스타일을 주는 건 depth에 무관하게 적용되어 의도치 않은 스타일링이 될 수 있습니다. 클래스 셀렉터(ex. `.foo`)를 사용해주세요.
- tag selector는 해당 요소 뿐만 아니라 동일한 태그로 선언된 다른 요소들에게도 영향을 미칠 여지가 너무 많기 때문에 추후 유지보수에 악영향을 미칠 수 있습니다.
- 스타일링을 줄 때는 요소마다 className을 부여하셔서 스타일링을 주시는게 좋습니다.

2022-03-29 05:59 UTC, younuk23 commented on src/pages/Main/Main.js
> +import './Main.scss';
main.scss가 empty인데 import 한 이유가 있나요?

2022-03-29 05:59 UTC, younuk23 commented on src/pages/Main/Main.js
> +    <main className="container">
container라는 className은 어디서 스타일링을 해주고 있을까요?!

2022-03-29 07:49 UTC, sunnyfterrain commented on jsconfig.json
> -}
저부분을 넣고 scss import를 하면 자꾸 제 vscode가 강제 종료되는 현상이 있어 삭제 했습니다😭

2022-03-31 03:39 UTC, 201steve approved these changes

2022-03-31 04:06 UTC, sunnyfterrain commented on src/components/Header/Header.js
> -  return <div>Header</div>;
최상위 태그를 컴포넌트 이름과 동일하게 부여하였습니다.

2022-03-31 04:06 UTC, sunnyfterrain commented on src/components/Header/Header.scss
> +header {
기본 태그 선택자 대신 모두 클래스네임을 적용하였습니다.

2022-03-31 04:48 UTC, sunnyfterrain commented on src/components/Header/Header.scss
> +    flex-direction: column;
해당 속성은 필요가 없어 삭제하였습니다.

2022-03-31 04:49 UTC, sunnyfterrain commented on src/pages/Main/Main.js
> +    <main className="container">
현재는 main에 작업한 사항이 없어 삭제하였습니다.

2022-03-31 04:49 UTC, sunnyfterrain commented on src/components/Header/Header.scss
> +    h3 {
기본 태그 선택자를 없애고 모두 className으로 변경하였습니다.

2022-03-31 05:08 UTC, sunnyfterrain commented on src/pages/Main/Main.js
> +import './Main.scss';
삭제하였습니다!

2022-04-01 01:02 UTC, closed without merging