ADD: Main page Slide Main page 상품 리스트 구현
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend pull request #4
Opened 2022-04-04 02:36 UTC by nohnohnohnoh

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Main 페이지에 슬라이드 구현 버튼 슬라이드 구현 무한루프 슬라이드 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-04 08:05 UTC, younuk23 requested changes
고생하셨습니다 영완님 리뷰 확인 및 반영해주세요!!

2022-04-04 08:05 UTC, yeonuk-hwang commented on src/pages/Main/GoodsList/GoodsList.js
> +    <div>
전체적으로 최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅 하는 부분이 적용안되어있습니다. 이렇게 되면 동일한 className을 가진 다른 컴포넌트의 요소들에게도 영향을 미칠 수 있습니다.
**최상위 태그의 className을 컴포넌트 이름과 동일하게 부여한 뒤 그 className하위로 네스팅** 적용해주세요

예시)

```jsx
const ProductDetail = () => {

	return(
		<section className="productDetial">
			~~~~
		</section>
	)
}
```

2022-04-04 08:05 UTC, yeonuk-hwang commented on src/pages/Main/Main.js
> +const ImageData = [
상수데이터는 UPPERCASE + snake_case 로 작성해주는게 프로그래밍 컨벤션입니다!! 다른 개발자들이 봤을 때 이 값은 상수값이구나 라고 이해할 수 있게 컨벤션 잘 지켜서 작성해주세요!!

그리고, 이 상수데이터가 중요한게 아니라 컴포넌트가 이 파일에서 중요한 내용이니 컴포넌트 하단으로 위치를 조정해주는게 좋습니다!

2022-04-04 08:05 UTC, yeonuk-hwang commented on src/pages/Main/Main.js
> +import './components/ProductMainList/ProductMainList.scss';
컴포넌트는 독립적이고 재사용될 수 있어야 합니다.
어떤 컴포넌트에 대한 스타일시트에서 컴포넌트 외의 요소에 대해서 접근해서 스타일을 부여한다면 그 컴포넌트는 독립적이라고 볼 수 없습니다.
컴포넌트의 스타일 시트는 해당 컴포넌트에 대한 스타일만 진행해주세요!

위 내용과 연관되어서, 이 컴포넌트에서 ProductMainList의 scss를 import할 이유는 없습니다. 이 컴포넌트에서 필요한 스타일링은 이 컴포넌트의 scss파일에서 작성해주세요!

2022-04-04 08:05 UTC, yeonuk-hwang commented on src/pages/Main/Main.js
> +  const [data, setData] = useState([]);
사용되지 않고 있네요 삭제해주세요, 그리고 data등의 이름은 변수명으로 적절치못합니다 항상 의미가 명확하게 드러나는 네이밍을 지향해주세요

2022-04-04 08:05 UTC, yeonuk-hwang commented on src/pages/Main/Main.js
> +  // useEffect(() => {
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다! 
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2022-04-04 08:05 UTC, younuk23 commented on src/pages/Main/MainSection/MainSection.js
> +}
custom hook잘 찾아서 사용하셨네요, 다만 사용에 그치면 안됩니다.
항상 레퍼런스를 통해서 찾은 코드들은 이게 어떤식으로 동작하는지에 대해서 명확히 이해하고 사용해야합니다!

useInterval hook의 동작방법에 대해서 코멘트로 남겨주세요!

2022-04-04 08:05 UTC, younuk23 commented on src/pages/Main/MainSection/MainSection.scss
> +}
nesting 적용해주세요!

2022-04-04 08:05 UTC, younuk23 commented on src/pages/Main/MainSection/MainSection.js
> +      <div className="container-dots">
여기만 갑자기 snake_case를 className에 활용하네요!

어떤 컨벤션을 사용하는건 팀 안에서 정하는 문제지만 하나의 컨벤션으로 정해졌으면 해당 컨벤션 지켜서 사용해야합니다!

2022-04-04 08:05 UTC, younuk23 commented
그리고 PR 본문 좀 더 꼼꼼하게 작성해주시고 예시문장은 삭제해주세요~!

2022-04-04 09:37 UTC, nohnohnohnoh commented on src/pages/Main/MainSection/MainSection.js
> +}
useInterval 과 set interval 의 차이는 동적이라는 것입니다. useInterval Hook은 간격을 설정하고 마운트 해제 후 지웁니다 set interval 구성 요소 수명 주기 와 clearInterval이 연결되어 있는 것입니다. 즉, setinterval로 간격을 설정하고 지우게 하게끔 하는 코드를 작성하는 대신 useInterval을 사용해 간격을 설정하고 특정 지연이 있는 간격을 선언할 수 있습니다.
리뷰 감사합니다 코로나 시라고 들었는데 아픈데는 없으신가요? 몸조리 잘 하셔서 건강 챙기셨으면 좋겠습니다 ㅜ 리뷰요청에 관한 코멘트 남깁니다 감사합니다

2022-04-04 09:43 UTC, ghost commented on src/pages/Main/Main.js
> +  console.log(productData);
__[ESLint]__ Unexpected console statement. ([view](https://sider.review/gh/repos/474886364/pulls/4#issue-6853683))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-console` | `warn` | No |

References:
- <https://eslint.org/docs/rules/no-console>

You can [close this issue](https://sider.review/gh/repos/474886364/pulls/4#issue-6853683) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-05 07:22 UTC, younuk23 commented on src/pages/Main/MainSection/MainSection.js
> +}
👍

2022-04-05 07:22 UTC, younuk23 commented
리뷰 반영 중이신거죠? 추가작업 진행보다는 리뷰 반영 우선적으로 진행해주세요~!

2022-04-07 04:40 UTC, younuk23 approved these changes
LGTM

2022-04-07 04:40 UTC, merged