[31기 남용현] ADD: 상품 페이지 구현
wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend pull request #8
Opened 2022-04-04 03:15 UTC by sunnyfterrain

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 상품별 카테고리 페이지 구현
- 상품별 리스트 페이지 구현
- 상품별 상세페이지 구현 

<br />

## :: 구현 사항 설명 
1. 상품별 카테고리 페이지
2. 상품별 리스트 페이지
- mock 데이터를 이용 상품별 리스트 구현
3. 상품별 상세 페이지
4. 상세페이지, 리스트페이지 공용 사용

<br />

## :: 성장 포인트
- 처음엔 상품별 상세페이지 , 리스트페이지를 각각 따로 만들었으나, 생각을 잘못 했다고 생각하여 공용으로 쓰게 만들어 놓으니 훨신 더 깔끔해지고 불필요한 js 파일들이 줄게되었습니다.
- 앞으로 이런경우가 생기면 재사용 할 수 있는것은 최대한 재사용 하는 습관을 들여야겠습니다. 
<br />

## :: 기타 질문 및 특이 사항

2022-04-04 07:38 UTC, younuk23 requested changes
고생하셨습니다! 리뷰 확인 및 반영해주세요!

2022-04-04 07:38 UTC, younuk23 commented on src/Router.js
> +  const productData = useFruitzState();
Router에는 state를 안두는게 좋습니다. Router는 state를 이용해서 UI를 조작하는게 목적이 아니라 route를 설정하기 위한 컴포넌트니까요

productData 같은 경우에는 contextAPI로 contextProvider안에서는 다 접근가능하게 되어있으니까 여기서 props로 넘기는게 아니라, 필요한 컴포넌트에서 직접 꺼내서 쓰는 방식이 좋겠네요, 여기서 넘겨서 쓰면은 context 를 사용한 의미가 없어보입니다.

그리고 login 같은 경우도 context API로 만들어서 처리하는게 좋아보입니다!

2022-04-04 07:38 UTC, younuk23 commented on src/Router.js
> +  const [isLogin, setIsLogin] = useState(token ? true : false);
```suggestion
  const [isLogin, setIsLogin] = useState(!!token);
```

삼항연산자 쓰지 않고도 이런식으로 truthy or falsy 값들을 true or false 형태로 변환할 수 있습니다!

2022-04-04 07:38 UTC, younuk23 commented on src/Router.js
> +        />
```suggestion
        <Route
          path="/:product/fruit/detail/:id"
          element={<Detail productData={productData.data} />}
        />
```

다 작성하는게 아니라 동적라우팅 활용하는게 좋아보이네요!

2022-04-04 07:38 UTC, younuk23 commented on src/pages/Product/Beverage/Beverage.js
> +  console.log('쿼리 확인:', beverage);
sider 코멘트는 다 해결해주세요!

2022-04-04 07:38 UTC, younuk23 commented on src/pages/Product/Components/Detail/Detail.js
> +  };
setModal 함수를 그대로 쓰는것과 다른게 없는것 같네요!

2022-04-04 07:38 UTC, younuk23 commented on src/pages/Product/Components/Detail/Detail.js
> +  const [modal, setModal] = useState(0);
modal이라는 변수명만가지고는 어떤 걸 표현하려고 하는지 인식하기 어렵네요!

2022-04-04 07:38 UTC, younuk23 commented on src/pages/Product/Components/Detail/DetailBtn.js
> +    fetch('', {
```suggestion
    // TODO: API 연결
    fetch('', {
```


이경우에는 주석등으로 마킹해두는게 좋아보이네요

2022-04-04 07:38 UTC, younuk23 commented on src/pages/Product/Components/Detail/DetailSelect.js
> +    setInput(count + 1);
input과 count가 같은 것을 표현하기 위한 값이여서 같이 바꿔주는 것 같은데, 따로 두개의 state에서 관리하는 이유가 있나요?

2022-04-04 07:38 UTC, younuk23 commented on src/pages/Product/Components/ProductList/ProductList.js
> +      {productData.data.map(productList => {
productData, productList 등에서 이것이 어떤 정보를 표현하는지 명확히 이해하기 힘듭니다. 실제로 List가 아니라 하나의 product가 각 매개변수로 나오는 것 같고요

```suggestion
      {products.map(product => {
```

위 같은 형태가 되는게 가장 깔끔해보이네요!

2022-04-04 07:38 UTC, younuk23 commented on src/Router.js
> +        <Route path="/product/gifts" element={<Gifts />} />
이 컴포넌트들은 각자 최상위태그의 className을 제외하고는 다른 부분이 없어보이는데 매번 다른 component로 만든 이유가 혹시 있나요??

딱히 없다면 하나의 컴포넌트로 재사용해도 충분해보입니다!

2022-04-04 08:41 UTC, sunnyfterrain commented on src/pages/Product/Beverage/Beverage.js
> +  console.log('쿼리 확인:', beverage);
sider 수정 하였습니다

2022-04-04 10:52 UTC, sunnyfterrain commented on src/Router.js
> +  const [isLogin, setIsLogin] = useState(token ? true : false);
!! 에 대해서 잘 몰랐어서 다시한번 공부 했습니다 수정하였습니다!

2022-04-04 10:53 UTC, sunnyfterrain commented on src/Router.js
> +        />
동적라우팅으로 하였습니다. 추후에 쿼리스트링이나 더 나은방향으로 연구해보겠습니다.

2022-04-04 11:03 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/Detail.js
> +  };
수정하였습니다! 따로 함수를 만들고 함수명만 적어주느냐 바로 콜백함수로 setModal을 하느냐 고민하다가 후자로 수정하였습니다.

2022-04-04 11:25 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/DetailSelect.js
> +    setInput(count + 1);
상품페이지의 주문수량을 입력할 수 있는 부분인데, 카운트 업,다운 버튼을 눌러서 값을 바꿀수 있고 직접 수량인풋창에서 수량변경을 할수도 있고 직접 수량변경을 한 상태에서 업,다운버튼도 가능하도록 하기위해 한 것입니다. 따로 하니까 직접 입력은 안되더라구요..

2022-04-04 12:01 UTC, sunnyfterrain commented on src/pages/Product/Components/ProductList/ProductList.js
> +      {productData.data.map(productList => {
수정하였습니다! 앞으로 map의 매개변수도 이름을 잘 지어야겠다는 생각이 듭니다.

2022-04-04 12:17 UTC, sunnyfterrain commented on src/Router.js
> +        <Route path="/product/gifts" element={<Gifts />} />
지식이부족해서 잘 할 줄을 몰랐었습니다. 하나의 컴포넌트와 라우터로 수정하였습니다.

2022-04-04 12:21 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/Detail.js
> +  const [modal, setModal] = useState(0);
다른 이름으로 수정하였습니다!

2022-04-04 12:21 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/DetailBtn.js
> +    fetch('', {
추후에 해야할 것을 찾기 쉽도록 TODO 주석을 달아놓았습니다.

2022-04-04 15:34 UTC, sunnyfterrain commented on src/Router.js
> +  const productData = useFruitzState();
Router에 state와 login관련되것 빼고 context에 합쳐서 적용하였습니다.
스테이트도 넘길 수 있다는것을 잘 몰랐는데 이번기회에 알게되어 너무 좋습니다.

2022-04-04 15:38 UTC, ghost commented on src/pages/Product/Components/Detail/DetailSelect.js
> +        <img alt="upArrowImg" src="https://fritz.co.kr/img/btn_quantity_up.gif"/>
__[ESLint]__ Replace `·alt="upArrowImg"·src="https://fritz.co.kr/img/btn_quantity_up.gif"` with `⏎··········alt="upArrowImg"⏎··········src="https://fritz.co.kr/img/btn_quantity_up.gif"⏎········` ([view](https://sider.review/gh/repos/474886364/pulls/8#issue-6855659))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `prettier/prettier` | `error` | - |

References:
- <https://github.com/prettier/eslint-plugin-prettier#options>

You can [close this issue](https://sider.review/gh/repos/474886364/pulls/8#issue-6855659) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-04 15:38 UTC, ghost commented on src/pages/Product/Components/Detail/DetailSelect.js
> +        <img alt="downArrowImg" src="https://fritz.co.kr/img/btn_quantity_down.gif"/>
__[ESLint]__ Replace `·alt="downArrowImg"·src="https://fritz.co.kr/img/btn_quantity_down.gif"` with `⏎··········alt="downArrowImg"⏎··········src="https://fritz.co.kr/img/btn_quantity_down.gif"⏎········` ([view](https://sider.review/gh/repos/474886364/pulls/8#issue-6855660))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `prettier/prettier` | `error` | - |

References:
- <https://github.com/prettier/eslint-plugin-prettier#options>

You can [close this issue](https://sider.review/gh/repos/474886364/pulls/8#issue-6855660) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-04-05 02:02 UTC, younuk23 requested changes
반영안된 부분 및 추가 리뷰사항 있습니다 확인 및 반영해주세요!

2022-04-05 02:02 UTC, yeonuk-hwang commented on src/pages/Product/Components/ProductList/ProductList.js
> +      {productData.data.map(productList => {
반영이 안되있습니다.

2022-04-05 02:02 UTC, yeonuk-hwang commented on src/FruitContext.js
> +/* eslint-disable */
eslint-disable은 특별한 사유가 없는한 하지 않습니다.
eslint를 통해 미리 문제점을 찾으려고 하는건데 이걸 disabled 시킬꺼면 사용하는 의미가 없습니다.

2022-04-05 02:02 UTC, younuk23 commented on src/FruitContext.js
> +  const [isLogin, setIsLogin] = useState(!!token);
login에 관련된게 Fruitz context안에 한번에 들어있는것 보다는 별개의 Context에 들어있는게 좋아보이네요

2022-04-05 02:02 UTC, younuk23 commented on src/FruitContext.js
> +    console.log('ddd:', mockData);
console 꼼꼼하게 확인하고 삭제해주세요

2022-04-05 02:02 UTC, younuk23 commented on src/FruitContext.js
> +    // const productData = await fetch(`${API_URL}`).then(res => res.json());
code는 주석처리하지 말고 삭제해주세요!

2022-04-05 02:02 UTC, younuk23 commented on src/pages/Product/Components/Detail/Detail.js
> +  return (
return문 위에 공백 한줄둬서 다른 문맥들끼리 구분해주는게 가독성에 좋습니다.

2022-04-05 02:08 UTC, younuk23 requested changes
추가 코멘트 남겼습니다 확인해주세요!

그리고 어제 머지된 PR중 답글 요청한 코멘트 몇개 있습니다. 확인 후 답글 남겨주세요~!

2022-04-05 02:08 UTC, younuk23 commented on src/pages/Product/Components/Detail/Detail.js
> +  const [input, setInput] = useState(1);
변경이 발생하는 곳이 여려군데라도 값은 하나로 충분히 활용할 수 있어 보입니다 하나로 합쳐주세요

2022-04-05 02:08 UTC, younuk23 commented on src/FruitContext.js
> +export const FruitzProvider = ({ children }) => {
Context API 사용하는 것 팀원들과 합의된 사항인가요?
새로운 기술들을 이것저것 시도해보는 것은 좋지만, 함께하는 프로젝트에 적용할때는 팀원들에게 새로운 기술을 소개하고 이해시키고 승인받는 과정또한 필수입니다.

지금부터는 다른 팀원들도 이 Context API가 어떻게 돌아가는지, 어떤식으로 동작하는지는 이해할 수 있도록 공감대를 형성하고나서 도입해주세요

만약 다른 팀원들은 어떻게 되는지도 모르고 가져다 쓰기만 한다면 그건 옳은 방향이 아니니까요, 실제 현업에서도 프로젝트에 새로운 스택을 도입하는것은 많은 논의와 공감대를 형성하고 나서 진행하게 됩니다.

이부분 꼭 유의해주세요! 그리고 이부분 혹시 아직 팀원들에게 제대로 이해 및 공유가 안됬다면 진행될 수 있도록 해주세요

2022-04-05 03:14 UTC, sunnyfterrain commented on src/pages/Product/Components/ProductList/ProductList.js
> +      {productData.data.map(productList => {
착각하고 다른곳에 수정해버렸습니다. 다시 재 수정하였습니다.

2022-04-05 03:14 UTC, sunnyfterrain commented on src/FruitContext.js
> +/* eslint-disable */
삭제하였습니다!

2022-04-05 03:16 UTC, sunnyfterrain commented on src/FruitContext.js
> +    // const productData = await fetch(`${API_URL}`).then(res => res.json());
삭제하였습니다.

2022-04-05 03:16 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/Detail.js
> +  return (
수정하였습니다.

2022-04-05 03:19 UTC, sunnyfterrain commented on src/FruitContext.js
> +export const FruitzProvider = ({ children }) => {
컨텍스트에 대해 설명을 하고 같이 사용하기로 합의 했으나, 각자의 파일이 쪼개진 상태라 컨텍스트 부분이 머지가 되면 그때 다시 각자의 데이터를 받는 코드를 수정하기로 했습니다.

2022-04-05 03:34 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/Detail.js
> +  const [input, setInput] = useState(1);
하나로 합쳤습니다!

2022-04-05 07:23 UTC, younuk23 commented
- 사이더 코멘트 해결해주세요
- 기존 리뷰 중 반영 안된항목들 있습니다 반영해주세요!

2022-04-05 09:30 UTC, sunnyfterrain commented on src/FruitContext.js
> +    console.log('ddd:', mockData);
삭제 하였습니다!

2022-04-05 09:44 UTC, sunnyfterrain commented on src/FruitContext.js
> +  const [isLogin, setIsLogin] = useState(!!token);
따로 분리하여 별개의 context를 만들었습니다.

2022-04-06 02:03 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!

2022-04-06 02:03 UTC, younuk23 commented on src/pages/Product/Components/Detail/Detail.js
> +  return (
수정안되었습니다! 꼼꼼히 확인해주세요~!

2022-04-06 02:03 UTC, younuk23 commented on src/FruitContext.js
> +  const [dataValue, setDataValue] = useState({
dataValue라는 이름은 너무 추상적이네요 의미가 드러나게 수정해주세요!

2022-04-06 02:03 UTC, younuk23 commented on src/FruitContext.js
> +    product: [],
mock, product를 따로 구분해서 할 필요가 있을까요? 데이터가 목에서 오는지, 실제 API에서 오는지만 다르지 그걸 실제 저장할때 이건 목데이터야 이건 API에서 오는데이터야 라고 구분지어서 표현할 필요는 없어보이네요! 실제로 구분 안짓고 하나의 밸류안에 담아두면 나중에 API 주소만 바꾸면 되는데 지금은 키값등 다른 부분도 모두 수정이필요해보이는 구조네요!

2022-04-06 02:03 UTC, younuk23 commented on src/FruitContext.js
> +  });
```suggestion
  const [fruizs, setFruits] = useState([]);
```

2022-04-06 02:52 UTC, sunnyfterrain commented on src/pages/Product/Components/Detail/Detail.js
> +  return (
다시 재확인 하였습니다!

2022-04-06 03:09 UTC, sunnyfterrain commented on src/FruitContext.js
> +  const [dataValue, setDataValue] = useState({
mockData로 수정하였습니다!

2022-04-06 03:11 UTC, sunnyfterrain commented on src/FruitContext.js
> +    product: [],
네! 맞습니다. 구분 지을 필요없이 하나로 맞추었습니다!

2022-04-06 04:07 UTC, sunnyfterrain commented on src/FruitContext.js
> +  });
const [mockData, setMockData] = useState([]);
이렇게 목데이터에 관한 스테이트만 작성하였습니다.

2022-04-06 05:25 UTC, younuk23 commented on src/FruitContext.js
> +  });
용현님 Q&A 방으로 저 한번 찾아와주세요!

2022-04-06 06:21 UTC, sunnyfterrain commented on src/FruitContext.js
> +  });
수정하였습니다! 너무 일차원적 으로 생각했습니다. 하나의 변화가 일어나면 연속으로 변화가 일어나는걸 최소화 해야한다는 것을 깨달았습니다.

2022-04-06 09:33 UTC, younuk23 approved these changes
LGTM 👍

2022-04-06 09:34 UTC, merged